spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flx_rb
    username: shrikant
    password: kale
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: rcd-bld
server:
  port: '9092'