eureka:
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ServiceRegistry
server:
  port: '8761'
