spring:
  application:
    name: sink-service
  data:
    mongodb:
      username: admin
      password: admin
      port: '27017'
      database: flx
      repositories:
        enabled: 'true'
      authentication-database: admin